### ISSUE TITLE
A way to get several documents at once by submitting a list of ids

### ISSUE THREAD

**Issue by GavinMendelGleason** [terminusdb/terminusdb#1226]
Currently the document interface takes an id field, but it would be convenient to be able to supply a list of ids instead.

**Comment by UWN** [comment]
BTW, could not reply to your mail today, invalid address.

**Comment by matko** [comment]
@hoijnet just requested this too on discord. The workaround I gave is that you can use document queries to get the right results, but this is cumbersome, slow, and requires you to know the appropriate type.

Bumping this issue up on the backlog.

**Comment by hoijnet** [comment]
This would be awesome indeed, thanks @matko for looking into it! The reason I need it at the moment is due to #1910 .

**Comment by hoijnet** [comment]
This works mostly, but I note a few things, perhaps a separate bug request for them?
* `sendCustomRequest` in the JavaScript client lacks the ability to send the custom header `"X-HTTP-Method-Override": "GET",`
* Great news, type is not a required parameter, it works without
* There is an issue as the as_list parameter is not honored, returning a streaming JSON request instead of a nice array of objects (as I have not expored streaming JSON yet.

Most important is the honoring of the as_list in the experimental setup. This is how I requested using axios instead:

I adjusted the URL here, hope for correctness. Tested against TerminusCMS though.

```
      const result = await axios
        .post(
          `http://localhost:6363/api/document/${instance}/${dp}/local/branch/${branch}`,
          {
            params: {
              graph_type: "instance",
              as_list: "true",
              ids: docIds,
              // type: "Entity",
            },
          },
          {
            headers: {
              "X-HTTP-Method-Override": "GET",
            },
          }
        );
```

I get a result with the above, but as streaming JSON `{}{}` instead of a list `[{},{}]`, despite trying to set as_list to both `"true"` and `true` (string/boolean).

Let's see what can be done.
