### ISSUE TITLE
api:UnknownPrefixError for uri path containing colon (`:`)

### ISSUE THREAD

**Issue by dwinston** [terminusdb/terminusdb#1418]
```
terminusdb_client.errors.DatabaseError: The key 'Retrieval/2022-08-29_full:"coronal mass ejection"' is utilising an unknown prefix.
{
  "@type": "api:GetDocumentErrorResponse",
  "api:error": {
  "@type": "api:UnknownPrefixError",
  "api:key": "Retrieval/2022-08-29_full:\"coronal mass ejection\""
   },
  "api:message": "The key 'Retrieval/2022-08-29_full:\"coronal mass ejection\"' is utilising an unknown prefix.",
   "api:status": "api:failure"
}
```

**To Reproduce**
I try to load a document with @id `Retrieval/2022-08-29_full:"coronal mass ejection"` and get the above error.

I do not have time to make a minimal reproduction here, but I hope this is sufficient. My expectation is that a path segment after a type segment (e.g. "Retrieval/" for {"@type": "Retrieval"} above) may contain a colon in TerminusDB and prefix resolution will not be attempted in this case.

**Comment by matko** [comment]
The problem here is that we try to detect if you're intending to put a document under a particular prefix, and we do so by the presence of a ':'. If there is no ':', we assume that it has to go under the base prefix.

You can also explicitely say something has to go under the base prefix by specifying your id like so: `@base:Object/foo`. I'm not 100% sure if this will work when your id has a ':' in it though, but it is worth a try.

**Comment by matko** [comment]
Ok, this should now be fixed in main.

While it won't be possible to insert as `Retrieval/2022-08-29_full:"coronal mass ejection"` (as we have no way to tell that `Retrieval/2022-08-29` is not a prefix label), on the main branch it is now possible to insert as `@base:Retrieval/2022-08-29_full:"coronal mass ejection"`.

In the future, we should restrict what is actually allowed as prefixes, as the turtle standard (and related standards) do have a far more restricted set of what can be a proper prefix label. When such a restriction is in place, we could recognize the case above directly as an unprefixed id. For now though, use `@base`.

This is now usable on the main branch, and will be included in the next release. Since there's now a viable workaround I'll close this issue. I have opened #1445 for the further restriction of prefix space to allow unambiguous parsing of ids, even without `@base`.

**Comment by dwinston** [comment]
Excellent, thank you!
