### ISSUE TITLE
Documentation: Python Intro Tutorial

### ISSUE THREAD

**Issue by luke-feeney** [terminusdb/terminusdb#223]
This should be an introductory tutorial and not an installation guide:

https://terminusdb.github.io/terminusdb/#/Intro_Tutorials/Start_With_Python

The idea is to give people who have already installed the DB and the client a chance to try out the tool in an easy tutorial - ingest, query, schema and maybe some additional operation. But a simple getting started thing.

Could you take a look @Cheukting

**Comment by Cheukting** [comment]
## TerminusDB Client Python

The terminusdb_client library consists of 4 major components: WOQLClient, WOQLQuery, WOQLViews and WOQLDataFrame (optional, included only if installed with the [dataframe] option). In this guide, we will show the basic usage of each component. For detail documentation of the Python client, please refer to the [full documentation](https://terminusdb.github.io/terminusdb-client-python/).

## WOQLClient

A connection object that allows you to connect with the TerminusDB (local or remote) with basic auth. To create an client object, you will have to provide a URL to the server.

```python
from terminusdb_client import WOQLClient
client = WOQLClient("https://127.0.0.1:6363/, insecure=True")
```

For connection to a local server, we also have to set the insecure flag to True.

The most common way to use the client is to 1) connected to an existing database or 2) create a brand new database.

To connect to an existing database:

```python
client.connect(key="root", account="admin", user="admin", db="example_db")
```

To create a new database:
```python
client.connect(key="root", account="admin", user="admin")
client.create_database("example_db")
```

##WOQLQuery

The WOQLQuery object provides a query building tool for WOQL query, instead of JSON-LD -- the native format of WOQL. Most WOQLQuery object methods return a WOQLQuery object that is chainable, one of the exceptions is `execute` which will send the query built with the client provided.

```python
from terminusdb_client import WOQLQuery as wq
conditions = [wq().triple("v:Journey", "type", "scm:Journey"),
              wq().triple("v:Journey", "start_station", "v:Start"),
              wq().opt().triple("v:Start", "label", "v:Start_Label"),
              wq().triple("v:Journey", "end_station", "v:End"),
              wq().opt().triple("v:End", "label", "v:End_Label"),
              wq().triple("v:Journey", "journey_bicycle", "v:Bike")]
query = wq().select("v:Start", "v:Start_Label", "v:End",  "v:End_Label").woql_and(*conditions)
query.execute(client)
```

**Comment by Cheukting** [comment]
Please try if the iframe works after putting it in place, if not let me know and I will replace it with a static png

**Comment by luke-feeney** [comment]
Looks good iframe seems to work
