### ISSUE TITLE
Displaying the Document ID when viewing a document

### ISSUE THREAD

**Issue by MrRaymondLee** [terminusdb/terminusdb#233]
The table of Documents doesn't allow clipboarding of Document ID.  When I click to view the object, it would be nice to see the Document ID in the table instead of getting it from the URL.

**Comment by KittyJose** [comment]
Hi MrRaymondLee, We may add a clipboard feature in to the table in future. In the meanwhile instead of getting the Document ID from the URL when you click to view the object the ID appears just below the Console Tab along with the type.


![image](https://user-images.githubusercontent.com/54106287/109672194-b0555980-7b6c-11eb-8338-21aba9de48ac.png)

**Comment by KittyJose** [comment]
Hi MrRaymondLee, So I have added a copy button to the doc view, its in dev as of now, after some testing will release it out yea. Closing this ticket as of now.
