### ISSUE TITLE
xsd:gYear and xdd:gYearRange quietly fail to cast.

### ISSUE THREAD

**Issue by jbennettgit** [terminusdb/terminusdb#242]
Ubuntu 18.04 running bootstrap version 4.1.2 in docker container, via python client:

The following queries:

WOQLQuery().cast('0123','xsd:gYear','v:Value').execute(client)
WOQLQuery().cast('0123','xdd:gYearRange','v:Value').execute(client)
WOQLQuery().cast('[0123,0456]','xdd:gYearRange','v:Value').execute(client)
etc.

All return the following.  No API error, no complaints:

{'@type': 'api:WoqlResponse', 'api:status': 'api:success', 'api:variable_names': ['Value'], 'bindings': [], 'deletes': 0, 'inserts': 0, 'transaction_retry_count': 0}

**Comment by GavinMendelGleason** [comment]
gYear, gYearRange, and other date objects which are not dateTime are currently not working in 4.2. We have a whitelist of xsd types which are known to work at: https://github.com/terminusdb/terminusdb/blob/master/docs/reference/XSD_WHITELIST.md

I realise that these are pretty important for Seshat and since they worked in previous iterations they were pretty pervasive, so I'll make sure to get them working again, hopefully in the next patch to 4.2.

**Comment by GavinMendelGleason** [comment]
Fixed in e28b1f4
