### ISSUE TITLE
Add commit ID to API requests and responses

### ISSUE THREAD

**Issue by Cheukting** [terminusdb/terminusdb#248]
Operation:
* The server will look for a certain HTTP header.
  * If the header is present, the server compares the commit ID with the latest commit ID. If these are different, the server responds with an error.
  * If the header is not present, do nothing.
* The server will include an HTTP header with the latest commit ID in the response.

Endpoints (`/api/...`):
* `document`
* `woql`
  * can query and update multiple databases (e.g. with `Using`)
  * use primary database only for now
* others in the future

Notes
* system and metadata need layer ID

**Comment by spl** [comment]
I've updated the title to reflect that we think it would be good to include the commit ID in any API response involving a query _or_ update of the data in the database. (I'm not sure if that is all API endpoints.) The idea is that a client can see the source commit for the response and can act on that, if desired.

**Comment by GavinMendelGleason** [comment]
Presumably we intend to return the commit id in the response headers so as not to break API?

**Comment by spl** [comment]
> Presumably we intend to return the commit id in the response headers so as not to break API?

That's a good idea.

**Comment by GavinMendelGleason** [comment]
For WOQL query responses it probably will not matter, but for the document interface I don't know where else we would put it...

**Comment by spl** [comment]
Why we should consider not using the term “commit ID”:
* Not every database has a commit that can be identified: `_system`, `_meta`. For these, we use the layer identifier.
* Since the header value differs depending on the database, it would be better not to consider it an identifier, because identifier might have the implication that something specific can be identified, and that specific thing depends on which database is referenced.

Why we should consider using the term “database version” or, perhaps even better, “data version”:
* We don't have to explain what is identified, only what is versioned.
* It leads to simpler English usage: “The version of the data in the database differs from the expected version.”

**Comment by GavinMendelGleason** [comment]
Seems like a good idea.
