### ISSUE TITLE
Change branch strategy

### ISSUE THREAD

**Issue by matko** [terminusdb/terminusdb#345]
Currently we're developing in dev, and only merge to master when we release.

We've decided to change this to working in master (to be renamed to main) instead, and have a stable branch for the release.

This issue is for discussion of how to do this and what will go into this. @rrooij will take charge in this.

**Comment by spl** [comment]
What are all the repositories that this change applies to? I think at least:
* https://github.com/terminusdb/terminusdb
* https://github.com/terminusdb/terminusdb-client-js

**Comment by spl** [comment]
Also, documentation such as `Contributing.md` (and others?) will need to be updated.

**Comment by spl** [comment]
This isn't strictly part of the issue, but, if we're going to change branch names in multiple repositories, should we go ahead and do it in _all_ the repositories? Not that I want to add more work to this issue, but I think it will reduce the cognitive load in the longer term:

1. Assuming we eventually want `main` instead of `master` everywhere, it would be easier to change them all in one go. In particular, each of us only has to go through the branch renaming steps on our local repositories once for each clone we have.
2. We won't have to remember which repository uses `master` and which one uses `main` because they will all use `main`. I can imagine the confusion I would have if my “hand memory” cannot remember which word to type when I switch from one to the other.
