### ISSUE TITLE
problem with | in organization name

### ISSUE THREAD

**Issue by Francesca-Bit** [terminusdb/terminusdb#929]
if the organization name has a  |  like Francesca-Bit|9e7d

when I try to can the server 
http://localhost:4242/Francesca-Bit%7C9e73/api/db/Francesca-Bit%7C9e73/test01

I got the following error:
```
{
  "api:message":"Error: invalid_organization_name(\"Francesca-Bit|9e73\")",
  "api:status":"api:server_error"
}
```

**Comment by matko** [comment]
The underlying cause is that we generate the label name for the database metadata graph (the top-level graph) as '<organization_name>|<database_name>'. If either of those contains a pipe character of their own, we're no longer able to properly split the label name apart.

If we wish to support names with pipes in them, we probably have to do an extra escape for the components to ensure that no pipe appears in them. Problem is, we already have a whole bunch of existing database labels around in existing terminusdb instances.

Maybe there's a way to escape just the pipe character in some special backwards compatible way?

**Comment by matko** [comment]
A possible solution is to use '||' (a double pipe character) as an escape in the components. It'll make the splitting logic a little bit more hairy (can't just split on pipe, have to check if it is part of an escape), but that should be doable.

**Comment by GavinMendelGleason** [comment]
Is there any reason anymore to have the separator be a pipe at all? We should just be using an explicit key.

**Comment by matko** [comment]
What do you mean by explicit key?
